name: Deploy to Firebase
'on':
  workflow_run:
    workflows: ['Test']
    types:
      - completed

jobs:
  build_and_deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx nx affected --target=deploy-firebase
        name: Deploying to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TFM_COMPANION }}
